### ISSUE TITLE
Will you also add a Tailwind config?

### ISSUE THREAD

**Issue by AdamQuadmon** [MafinBoy/next-themes-hydration#1]
Nice one!
Trying NextJs 13 withApp Router gets me back to my AngularJs alpha experience 10 years ago!
It's like surfing on the edge coding watching for the next wave to come.

I saw your comment here https://github.com/pacocoursey/next-themes/issues/169 and I found this repo

Will you also add the Middleware and a Tailwind config?

Did you find any issues with this implementation?

**Comment by MafinBoy** [comment]
> Trying NextJs 13 withApp Router gets me back to my AngularJs alpha experience 10 years ago!
> It's like surfing on the edge coding watching for the next wave to come.

Haha, I wasn't in the dev space back then, but I'm sure it must have been hell of a ride.
The App Router adds a lot of new functionality and with that new possibilities!

> Will you also add the Middleware and a Tailwind config?

Yeah, sure, I can add Tailwind but I'm not sure what you'd want middleware for here?

> Did you find any issues with this implementation?

The point of this project is to render everything on the server and get rid of hydration mismatch completely.
With that in mind I'm currently trying to find a way to resolve user's system theme before anything gets rendered on the server, but for now I wasn't able to do it.
Unless I'm missing something I'm afraid it might not be possible with current NextJS toolkit.

**Comment by AdamQuadmon** [comment]
> > Will you also add the Middleware and a Tailwind config?
> 
> Yeah, sure, I can add Tailwind but I'm not sure what you'd want middleware for here?

Sorry, I just missed your ThemedHTML implementation

> The point of this project is to render everything on the server and get rid of hydration mismatch completely. With that in mind I'm currently trying to find a way to resolve user's system theme before anything gets rendered on the server, but for now I wasn't able to do it. Unless I'm missing something I'm afraid it might not be possible with current NextJS toolkit.


Have you checked `Sec-CH-Prefers-Color-Scheme` request header?

https://caniuse.com/mdn-http_headers_sec-ch-prefers-color-scheme

I love the idea of rendering everything on the server to not pollute the client.

In my scenario I will be happy to start Dark mode and give the user the possibility to switch to Light  if `window.matchMedia('(prefers-color-scheme: light)')`, maybe with a tooltip.

But still I'm too rusty, I spent last 2 weeks trying to fill the gap of more than 2 years off of the keyboard, and I still haven't found a good way to separate dark and light styles.

Using Tailwind in NextJs 13 as CSS module there is an abuse of `@apply`, things get worst when you try to add the `.dark` variant, I tried this but is not working and I don't like it:

```css
.nav {
  @apply bg-gray-200;
}

:global(.dark) .nav {
  @apply bg-gray-800;
}
```

will be nicer to just have:

```css
.nav{
  @apply bg-color;
}
/* or */

.nav {
   background-color: rgb(var(--foreground-rgb));
}
```

can we just import the realative `colors-light.css` or `colors-dark.css` in the global.css file?

**Comment by AdamQuadmon** [comment]
Have you considered Server Actions for the toggler?

```ts
'use server';

import { cookies } from 'next/headers';

const validThemes = ['dark', 'light'];
const defaultTheme = 'dark';

export const setTheme = async (theme: string) => {
  theme = validThemes.includes(theme) ? theme : defaultTheme;
  cookies().set('theme', theme, {
    httpOnly: true,
    secure: true,
    sameSite: 'strict',
    expires: new Date(2147483647 * 1000)
  });
};
```

**Comment by MafinBoy** [comment]
> Have you checked `Sec-CH-Prefers-Color-Scheme` request header?
> 
> https://caniuse.com/mdn-http_headers_sec-ch-prefers-color-scheme

Unfortunately this doesn't have enough browser support.
Even my Chrome 114 instance which technically *should* have this feature, doesn't (at least not by default).

> Have you considered Server Actions for the toggler?

I don't think that would make any difference, it would just generate unnecessary internet traffic.

**Comment by MafinBoy** [comment]
> Using Tailwind in NextJs 13 as CSS module there is an abuse of `@apply`, things get worst when you try to add the `.dark` variant, I tried this but is not working and I don't like it:

I would just do it [how Tailwind recommends to do it](https://tailwindcss.com/docs/dark-mode):
```css
.nav {
  @apply bg-gray-200 dark:bg-gray-800;
}
```
and to get the `dark:` property to work with this repo just add this to your `tailwind.config.js`:
```js
module.exports = {
  darkMode: ["class", '[data-theme="dark"]'],
};

```

**Comment by MafinBoy** [comment]
> Using Tailwind in NextJs 13 as CSS module there is an abuse of `@apply`, things get worst when you try to add the `.dark` variant, I tried this but is not working and I don't like it:

I would just do it [how Tailwind recommends to do it](https://tailwindcss.com/docs/dark-mode):
```css
.nav {
  @apply bg-gray-200 dark:bg-gray-800;
}
```
and to get the `dark:` property to work with this repo just add this to your `tailwind.config.js`:
```js
module.exports = {
  darkMode: ["class", '[data-theme="dark"]'],
};

```

**Comment by jthrilly** [comment]
> With that in mind I'm currently trying to find a way to resolve user's system theme before anything gets rendered on the server, but for now I wasn't able to do it.

I appreciate this is out of scope for this library, but if the user's preference was stored on the server (say in a DB) wouldn't that resolve this issue?

**Comment by MafinBoy** [comment]
> I appreciate this is out of scope for this library, but if the user's preference was stored on the server (say in a DB) wouldn't that resolve this issue?

Not really, because if we store user's system theme in a db and the user changes it between visits to the website, the db won't have up to date information, which would cause a visible flash.

**Comment by MafinBoy** [comment]
Tailwind was added in caaf30c.
Closing this issue.
